In [1]:
from __future__ import annotations

import duckdb
import pandas as pd

from lake_client import LAKE_SOURCE, describe, list_tables, load_table
from etl import config as C

pd.set_option("display.max_columns", 60)
pd.set_option("display.width", 200)

describe()

LAKE_SOURCE = 's3'  ->  online (remote URIs from .env)
target_uri  = s3://loka-test-poc-201302614689-us-east-1

  bronze       7 table(s): bronze_device_metadata, bronze_heart_rate, bronze_participants, bronze_sleep_sessions, bronze_sleep_stages, bronze_steps, bronze_wellness_survey
  silver       8 table(s): silver_devices, silver_heart_rate_minute, silver_participant_day_coverage, silver_participants, silver_sleep_sessions, silver_sleep_stages, silver_steps_minute, silver_wellness_survey
  gold         5 table(s): _analytics, gold_chronotype_cohort_metrics, gold_daily_participant_metrics, gold_participant_devices, gold_weekly_participant_summary
  _quarantine  2 table(s): sleep_sessions, wellness_survey
  _dq          1 table(s): dq_checks

## Bronze — verbatim + lineage

Nothing is cleaned here. Timestamps are still strings, sentinels are still
in the data, the undocumented unit field (if present) is still whatever it
was called in the export. The three lineage columns show where every row
came from and which run landed it.

In [8]:
bronze_steps = load_table(C.BRONZE, "bronze_steps")
print(bronze_steps.shape)
bronze_steps.head()

(2014950, 8)

             timestamp  steps participant_id                                        _source_uri               _ingested_at               _run_id _unit _source_participant_dir
0  2026-01-08T00:00:00      0           P001  s3://de-tech-assessment-396587179375-us-east-1... 2026-09-22 00:23:00.394958  run_20260922T002259Z  <NA>                    P001
1  2026-01-08T00:01:00      0           P001  s3://de-tech-assessment-396587179375-us-east-1... 2026-09-22 00:23:00.394958  run_20260922T002259Z  <NA>                    P001
2  2026-01-08T00:02:00      2           P001  s3://de-tech-assessment-396587179375-us-east-1... 2026-09-22 00:23:00.394958  run_20260922T002259Z  <NA>                    P001
3  2026-01-08T00:03:00      0           P001  s3://de-tech-assessment-396587179375-us-east-1... 2026-09-22 00:23:00.394958  run_20260922T002259Z  <NA>                    P001
4  2026-01-08T00:04:00      0           P001  s3://de-tech-assessment-396587179375-us-east-1... 2026-09-22 00:23:00.394958  run_20260922T002259Z  <NA>                    P001

In [ ]:
bronze_sleep_sessions = load_table(C.BRONZE, "bronze_sleep_sessions")
print(bronze_sleep_sessions.shape)
bronze_sleep_sessions.head()

(1400, 11)

,session_key,date,sleep_onset,sleep_end,efficiency_pct,restlessness,n_stages,_source_uri,_ingested_at,_run_id,participant_id
0,P001|2026-01-08,2026-01-08,2026-01-07T22:54:29.000,2026-01-08T07:04:29.000,100.0,0.077604,5,s3://de-tech-assessment-396587179375-us-east-1...,2026-09-22 00:23:00.394958,run_20260922T002259Z,P001
1,P001|2026-01-09,2026-01-09,2026-01-08T23:29:00.000,2026-01-09T06:00:00.000,100.0,0.067431,5,s3://de-tech-assessment-396587179375-us-east-1...,2026-09-22 00:23:00.394958,run_20260922T002259Z,P001
2,P001|2026-01-10,2026-01-10,2026-01-09T22:55:49.000,2026-01-10T05:01:49.000,100.0,0.073871,5,s3://de-tech-assessment-396587179375-us-east-1...,2026-09-22 00:23:00.394958,run_20260922T002259Z,P001
3,P001|2026-01-11,2026-01-11,2026-01-10T22:51:49.000,2026-01-11T06:35:49.000,100.0,0.027270,5,s3://de-tech-assessment-396587179375-us-east-1...,2026-09-22 00:23:00.394958,run_20260922T002259Z,P001
4,P001|2026-01-12,2026-01-12,2026-01-11T22:24:08.000,2026-01-12T05:26:08.000,100.0,0.114297,5,s3://de-tech-assessment-396587179375-us-east-1...,2026-09-22 00:23:00.394958,run_20260922T002259Z,P001

In [ ]:
bronze_sleep_stages = load_table(C.BRONZE, "bronze_sleep_stages")
print(bronze_sleep_stages.shape)
bronze_sleep_stages.head(6)

(7000, 11)

,session_key,date,stage_idx,stage,start_time,end_time,duration_min,_source_uri,_ingested_at,_run_id,participant_id
0,P001|2026-01-08,2026-01-08,0,light,2026-01-07T22:54:29.000,2026-01-08T01:15:29.000,141,s3://de-tech-assessment-396587179375-us-east-1...,2026-09-22 00:23:00.394958,run_20260922T002259Z,P001
1,P001|2026-01-08,2026-01-08,1,deep,2026-01-08T01:15:29.000,2026-01-08T02:47:29.000,92,s3://de-tech-assessment-396587179375-us-east-1...,2026-09-22 00:23:00.394958,run_20260922T002259Z,P001
2,P001|2026-01-08,2026-01-08,2,rem,2026-01-08T02:47:29.000,2026-01-08T04:42:29.000,115,s3://de-tech-assessment-396587179375-us-east-1...,2026-09-22 00:23:00.394958,run_20260922T002259Z,P001
3,P001|2026-01-08,2026-01-08,3,light,2026-01-08T04:42:29.000,2026-01-08T07:04:29.000,142,s3://de-tech-assessment-396587179375-us-east-1...,2026-09-22 00:23:00.394958,run_20260922T002259Z,P001
4,P001|2026-01-08,2026-01-08,4,awake,2026-01-08T07:04:29.000,2026-01-08T08:15:29.000,71,s3://de-tech-assessment-396587179375-us-east-1...,2026-09-22 00:23:00.394958,run_20260922T002259Z,P001
5,P001|2026-01-09,2026-01-09,0,light,2026-01-08T23:29:00.000,2026-01-09T01:18:00.000,109,s3://de-tech-assessment-396587179375-us-east-1...,2026-09-22 00:23:00.394958,run_20260922T002259Z,P001

## Silver — cleaned, typed, flagged

Every correction leaves a boolean flag column behind rather than
disappearing silently — `was_rescaled`, `was_sentinel`, `is_stuck`, etc.

In [30]:
silver_participants = load_table(C.SILVER, "silver_participants")
print(silver_participants.shape)
silver_participants.head()

(50, 7)

  participant_id          device_id  age  height_cm  gender chronotype  max_heart_rate
0           P001  FBT-0001-9D79801C   38        183    male          B             167
1           P002  FBT-0002-D11AD6BD   31        181    male          A             199
2           P003  FBT-0003-5752B13E   51        177    male          B             179
3           P004  FBT-0004-DE56B823   26        177    male          A             188
4           P005  FBT-0005-A9603D1A   40        182  female          A             193

In [ ]:
silver_hr = load_table(C.SILVER, "silver_heart_rate_minute")
print(silver_hr.shape)
silver_hr.head()

(2009160, 8)

  participant_id           timestamp  heart_rate_bpm  is_stuck  was_utc  was_off_minute  was_out_of_range        date
0           P001 2026-01-08 00:00:00              59     False    False           False             False  2026-01-08
1           P001 2026-01-08 00:01:00              58     False    False           False             False  2026-01-08
2           P001 2026-01-08 00:02:00              57     False    False           False             False  2026-01-08
3           P001 2026-01-08 00:03:00              57     False    False           False             False  2026-01-08
4           P001 2026-01-08 00:04:00              56     False    False           False             False  2026-01-08

In [16]:
# How many minutes were actually touched by each rule, on this run:
silver_hr[["was_utc", "was_off_minute", "was_out_of_range", "is_stuck"]].sum()

was_utc             2880
was_off_minute        10
was_out_of_range       4
is_stuck             360
dtype: int64

In [16]:
silver_steps = load_table(C.SILVER, "silver_steps_minute")
print(silver_steps.shape)
silver_steps.head()

(2009160, 9)

  participant_id           timestamp  steps unit_raw  was_rescaled  was_utc  was_off_minute  was_sentinel        date
0           P001 2026-01-08 00:00:00      0     <NA>         False    False           False         False  2026-01-08
1           P001 2026-01-08 00:01:00      0     <NA>         False    False           False         False  2026-01-08
2           P001 2026-01-08 00:02:00      2     <NA>         False    False           False         False  2026-01-08
3           P001 2026-01-08 00:03:00      0     <NA>         False    False           False         False  2026-01-08
4           P001 2026-01-08 00:04:00      0     <NA>         False    False           False         False  2026-01-08

In [18]:
silver_steps[['was_rescaled', 'was_utc', 'was_off_minute', 'was_sentinel']].sum()

was_rescaled      120958
was_utc                0
was_off_minute        10
was_sentinel           4
dtype: int64

In [19]:
silver_sleep_sessions = load_table(C.SILVER, "silver_sleep_sessions")
print(silver_sleep_sessions.shape)
silver_sleep_sessions.head()

(1393, 21)

,session_key,participant_id,date,sleep_onset,sleep_end,mid_sleep_time,mid_sleep_hour_signed,sleep_onset_hour_signed,total_sleep_min,time_in_bed_min,sleep_efficiency_pct,deep_sleep_pct,rem_sleep_pct,light_min,deep_min,rem_min,awake_min,restlessness,efficiency_pct_stated,n_stages,stage_order_canonical
0,P001|2026-01-08,P001,2026-01-08,2026-01-07 22:54:29,2026-01-08 07:04:29,2026-01-08 02:59:29,2.991389,-1.100000,490.0,561.0,87.344029,18.775510,23.469388,283.0,92.0,115.0,71.0,0.077604,100.0,5,True
1,P001|2026-01-09,P001,2026-01-09,2026-01-08 23:29:00,2026-01-09 06:00:00,2026-01-09 02:44:30,2.741667,-0.516667,391.0,442.0,88.461538,28.132992,15.856777,219.0,110.0,62.0,51.0,0.067431,100.0,5,True
2,P001|2026-01-10,P001,2026-01-10,2026-01-09 22:55:49,2026-01-10 05:01:49,2026-01-10 01:58:49,1.980278,-1.083333,366.0,405.0,90.370370,19.672131,22.404372,212.0,72.0,82.0,39.0,0.073871,100.0,5,True
3,P001|2026-01-11,P001,2026-01-11,2026-01-10 22:51:49,2026-01-11 06:35:49,2026-01-11 02:43:49,2.730278,-1.150000,464.0,521.0,89.059501,21.551724,18.965517,276.0,100.0,88.0,57.0,0.027270,100.0,5,True
4,P001|2026-01-12,P001,2026-01-12,2026-01-11 22:24:08,2026-01-12 05:26:08,2026-01-12 01:55:08,1.918889,-1.600000,422.0,478.0,88.284519,9.478673,17.061611,310.0,40.0,72.0,56.0,0.114297,100.0,5,True

In [20]:
silver_sleep_stages = load_table(C.SILVER, "silver_sleep_stages")
print(silver_sleep_stages.shape)
silver_sleep_stages.head()

(6965, 11)

       session_key participant_id        date  stage_idx  stage  is_asleep          start_time            end_time  duration_min_stated  duration_min_derived  duration_mismatch
0  P001|2026-01-08           P001  2026-01-08          0  light       True 2026-01-07 22:54:29 2026-01-08 01:15:29                  141                 141.0              False
1  P001|2026-01-08           P001  2026-01-08          1   deep       True 2026-01-08 01:15:29 2026-01-08 02:47:29                   92                  92.0              False
2  P001|2026-01-08           P001  2026-01-08          2    rem       True 2026-01-08 02:47:29 2026-01-08 04:42:29                  115                 115.0              False
3  P001|2026-01-08           P001  2026-01-08          3  light       True 2026-01-08 04:42:29 2026-01-08 07:04:29                  142                 142.0              False
4  P001|2026-01-08           P001  2026-01-08          4  awake      False 2026-01-08 07:04:29 2026-01-08 08:15:29                   71                  71.0              False

In [21]:
silver_wellness_survey = load_table(C.SILVER, "silver_wellness_survey")
print(silver_wellness_survey.shape)
silver_wellness_survey.head()

(1400, 6)

  participant_id        date  fatigue_score  stress_score  readiness_score  sleep_quality_score
0           P001  2026-01-08              3             3                8                    3
1           P001  2026-01-09              3             3                6                    3
2           P001  2026-01-10              3             3                3                    2
3           P001  2026-01-11              3             3                5                    3
4           P001  2026-01-12              3             3                6                    3

In [29]:
silver_participant_day_coverage = load_table(C.SILVER, "silver_participant_day_coverage")
print(silver_participant_day_coverage.shape)
silver_participant_day_coverage.head()

(1400, 11)

  participant_id        date  steps_minutes  hr_minutes  sleep_sessions  survey_responses  steps_coverage_pct  hr_coverage_pct  coverage_pct  is_complete_day  is_missing_day
0           P001  2026-01-08           1440        1440               1                 1               100.0            100.0         100.0             True           False
1           P001  2026-01-09           1440        1440               1                 1               100.0            100.0         100.0             True           False
2           P001  2026-01-10           1440        1440               1                 1               100.0            100.0         100.0             True           False
3           P001  2026-01-11           1440        1440               1                 1               100.0            100.0         100.0             True           False
4           P001  2026-01-12           1440        1440               1                 1               100.0            100.0         100.0             True           False

## Quarantine — rejected, not dropped

Sleep sessions and survey rows that couldn't be repaired land here instead
of Silver, with the reason attached, instead of silently vanishing.

In [23]:
if "sleep_sessions" in list_tables(C.QUARANTINE):
    quarantined_sleep = load_table(C.QUARANTINE, "sleep_sessions")
    print(quarantined_sleep.shape)
    quarantined_sleep["reject_reason"].value_counts()
else:
    print("no quarantined sleep sessions on this run")

(7, 22)

## Gold — the four analysis-ready tables

All four are chained SQL views over Silver (see `poc/sql/`), so they are
always consistent with each other on a given run.

In [24]:
gold_tables = {
    name: load_table(C.GOLD, name)
    for name in (
        "gold_participant_devices",
        "gold_daily_participant_metrics",
        "gold_weekly_participant_summary",
        "gold_chronotype_cohort_metrics",
    )
}
for name, df in gold_tables.items():
    print(f"{name:<34} {df.shape}")

gold_participant_devices           (50, 11)
gold_daily_participant_metrics     (1400, 39)
gold_weekly_participant_summary    (250, 39)
gold_chronotype_cohort_metrics     (12, 27)

In [25]:
gold_tables["gold_daily_participant_metrics"].head()

,participant_id,study_week,study_day,chronotype_declared,age,gender,max_heart_rate,steps_total,active_minutes,steps_peak_minute,activity_midpoint_hour,hr_mean_bpm,hr_resting_bpm,hr_min_bpm,hr_max_bpm,total_sleep_min,time_in_bed_min,sleep_efficiency_pct,deep_sleep_pct,rem_sleep_pct,mid_sleep_hour,sleep_onset_hour,restlessness,fatigue_score,stress_score,readiness_score,sleep_quality_score,steps_minutes,hr_minutes,coverage_pct,is_complete_day,is_missing_day,has_sleep_session,has_survey,minutes_nulled,minutes_unit_rescaled,hr_stuck_minutes,minutes_tz_corrected,date
0,P001,1,1,B,38,male,167,8523.0,925,32,14.070,60.3,55.0,49,74,490.0,561.0,87.34,18.78,23.47,2.991,-1.100,0.077604,3,3,8,3,1440,1440,100.0,True,False,True,True,0,0,0,0,2026-01-08
1,P002,1,1,A,31,male,199,6584.0,919,26,14.093,70.3,65.0,61,82,401.0,454.0,88.33,2.99,18.70,2.859,-0.483,0.071804,4,3,7,3,1440,1440,100.0,True,False,True,True,0,0,0,0,2026-01-08
2,P003,1,1,B,51,male,179,8298.0,938,32,14.105,65.7,60.0,55,81,402.0,466.0,86.27,9.20,19.65,3.530,0.167,0.103476,3,2,4,4,1440,1440,100.0,True,False,True,True,0,0,0,0,2026-01-08
3,P004,1,1,A,26,male,188,10275.0,943,40,14.153,67.7,62.0,58,83,309.0,347.0,89.05,10.68,22.98,2.064,-0.517,0.043776,3,2,4,2,1440,1440,100.0,True,False,True,True,0,0,0,0,2026-01-08
4,P005,1,1,A,40,female,193,2695.0,851,11,13.923,104.5,69.0,65,135,455.0,530.0,85.85,11.43,18.90,1.857,-1.950,0.139491,4,4,7,4,1440,1440,100.0,True,False,True,True,0,1440,0,0,2026-01-08

In [26]:
gold_tables["gold_chronotype_cohort_metrics"].head()

,period_type,period_label,study_week,chronotype,n_participants,n_participant_days,n_complete_days,n_nights,mid_sleep_hour_mean,mid_sleep_hour_sd,mid_sleep_hour_median,sleep_onset_hour_mean,total_sleep_min_mean,total_sleep_min_sd,sleep_efficiency_pct_mean,deep_sleep_pct_mean,rem_sleep_pct_mean,restlessness_mean,activity_midpoint_hour_mean,steps_total_mean,steps_total_sd,active_minutes_mean,hr_resting_bpm_mean,fatigue_score_mean,stress_score_mean,readiness_score_mean,sleep_quality_score_mean
0,week,1,1,A,28,112,109,111,2.675,1.017,2.719,-0.866,424.0,80.1,86.60,17.74,19.46,0.0952,13.998,8885.7,2535.8,932.0,62.28,2.58,2.93,4.92,2.74
1,week,1,1,B,22,88,87,88,2.357,0.985,2.371,-0.972,398.6,71.2,87.33,18.60,22.10,0.0879,14.005,9031.6,2857.1,931.1,62.67,2.63,2.98,5.01,2.70
2,week,2,2,A,28,196,195,194,2.605,0.996,2.623,-0.864,415.3,82.6,87.19,17.97,20.31,0.0915,14.012,8864.6,2535.4,932.2,62.47,2.70,2.86,4.99,2.68
3,week,2,2,B,22,154,154,154,2.468,0.900,2.547,-0.898,402.9,78.3,87.17,18.35,21.04,0.0921,13.998,9039.1,2863.1,931.9,62.81,2.69,2.98,5.07,2.64
4,week,3,3,A,28,196,196,194,2.499,0.965,2.481,-0.889,405.7,79.3,87.40,17.49,20.58,0.0940,14.002,8891.3,2521.6,932.0,62.39,2.68,2.88,4.85,2.69

In [27]:
gold_tables["gold_participant_devices"].head()

  participant_id          device_id     device_model          wear_site calibration_date firmware_version   firmware_source  age  gender chronotype_declared  max_heart_rate
0           P001  FBT-0001-9D79801C  Fitbit Charge 5  wrist_nondominant       2025-12-24            2.2.0  firmware_version   38    male                   B             167
1           P002  FBT-0002-D11AD6BD  Fitbit Charge 5     wrist_dominant       2025-12-18            2.2.0  firmware_version   31    male                   A             199
2           P003  FBT-0003-5752B13E  Fitbit Charge 5     wrist_dominant       2026-01-04            2.2.0  firmware_version   51    male                   B             179
3           P004  FBT-0004-DE56B823  Fitbit Charge 5  wrist_nondominant       2025-12-30            2.2.1  firmware_version   26    male                   A             188
4           P005  FBT-0005-A9603D1A  Fitbit Charge 5     wrist_dominant       2026-01-05            2.2.1  firmware_version   40  female                   A             193

In [28]:
gold_tables["gold_weekly_participant_summary"].head()

,participant_id,study_week,week_start,week_end,chronotype_declared,age,gender,days_in_week,days_complete,days_missing,nights_with_sleep,days_with_survey,mean_coverage_pct,steps_total_mean,steps_total_sd,steps_total_sum,active_minutes_mean,activity_midpoint_hour_mean,hr_resting_bpm_mean,hr_resting_bpm_sd,hr_mean_bpm_mean,hr_max_bpm_week,total_sleep_min_mean,total_sleep_min_sd,sleep_efficiency_pct_mean,sleep_efficiency_pct_sd,deep_sleep_pct_mean,rem_sleep_pct_mean,mid_sleep_hour_mean,mid_sleep_hour_sd,sleep_onset_hour_mean,restlessness_mean,fatigue_score_mean,stress_score_mean,readiness_score_mean,sleep_quality_score_mean,minutes_nulled,hr_stuck_minutes,minutes_unit_rescaled
0,P001,1,2026-01-08,2026-01-11,B,38,male,4,4,0,4,4,100.0,8452.3,189.4,33809.0,931.0,14.026,52.00,6.00,59.93,74,427.8,58.7,88.81,1.26,22.03,20.17,2.611,0.437,-0.963,0.0615,3.00,3.00,5.50,2.75,0.0,0.0,0.0
1,P001,2,2026-01-12,2026-01-18,B,38,male,7,7,0,7,7,100.0,8394.7,127.5,58763.0,930.4,14.009,55.29,0.49,60.50,74,401.1,82.6,87.81,3.02,16.18,20.62,2.665,0.822,-0.683,0.0794,3.00,3.14,4.29,3.00,0.0,0.0,0.0
2,P001,3,2026-01-19,2026-01-25,B,38,male,7,7,0,7,7,100.0,8564.7,158.2,59953.0,936.1,14.001,55.43,0.53,60.53,75,385.3,88.4,84.90,4.45,21.27,18.42,1.983,0.783,-1.236,0.0806,2.29,2.57,4.00,2.43,0.0,0.0,0.0
3,P001,4,2026-01-26,2026-02-01,B,38,male,7,7,0,7,7,100.0,8461.7,171.8,59232.0,936.9,13.996,55.29,0.49,60.49,75,414.6,63.1,87.88,3.14,19.78,18.68,2.457,0.524,-1.009,0.0896,2.86,3.00,4.86,2.71,0.0,0.0,0.0
4,P001,5,2026-02-02,2026-02-04,B,38,male,3,3,0,3,3,100.0,8538.0,153.9,25614.0,930.3,13.977,55.33,0.58,60.50,73,467.0,85.2,87.67,2.48,18.40,21.48,3.354,0.464,-0.545,0.1236,3.00,1.33,4.33,3.00,0.0,0.0,0.0

In [34]:
gold_tables["gold_weekly_participant_summary"]['chronotype_declared'].unique()

<ArrowStringArray>
['B', 'A']
Length: 2, dtype: str

## Data quality — every `Check` emitted on this run

One row per rule per table; `severity` is `error` (a handled source
defect), `warn`, `info`, or `assert_fail` (a pipeline invariant broken —
the thing `--strict` fails the run on).

In [20]:
dq = load_table(C.DQ, "dq_checks")
dq["severity"].value_counts()

severity
assert_pass    20
error          16
warn            3
info            2
Name: count, dtype: int64

In [21]:
dq.sort_values("n_affected", ascending=False)[
    ["table", "rule", "severity", "n_affected", "detail"]
].head(15)

                              table                            rule severity  n_affected                                             detail
18              silver_steps_minute     unit_field_nonstandard_name     warn      120963  unit arrives as `_unit`, not `unit`; resolved ...
13              silver_steps_minute                   unit_rescaled    error      120963  rows carried an hourly rate on a per-minute gr...
1          silver_heart_rate_minute          duplicate_rows_removed    error        5790  duplicate ('participant_id', 'timestamp') acro...
11              silver_steps_minute          duplicate_rows_removed    error        5790  duplicate ('participant_id', 'timestamp') acro...
4          silver_heart_rate_minute             timezone_normalised    error        2880  rows exported as Z-suffixed UTC, pulled back t...
39  silver_participant_day_coverage                       grid_size     info        1400                          50 participants x 28 days
17            silver_sleep_sessions       source_efficiency_ignored     warn        1132  1132/1400 sessions report efficiency_pct exact...
2          silver_heart_rate_minute            stuck_sensor_flagged    error         360  2 run(s) of >= 60 identical consecutive minute...
12              silver_steps_minute     timestamp_snapped_to_minute    error          28  seconds != 00; floored to the minute before de...
3          silver_heart_rate_minute     timestamp_snapped_to_minute    error          28  seconds != 00; floored to the minute before de...
16                   silver_devices  firmware_backfilled_from_label     warn          15  firmware_version blank; recovered by regex fro...
15           silver_wellness_survey       survey_orphan_participant    error          14  participant_id not in the roster; quarantined,...
8             silver_sleep_sessions            sessions_quarantined    error           7  rejected rather than repaired - the correct va...
10              silver_sleep_stages         stage_duration_mismatch    error           4  duration_min disagrees with the timestamps on ...
6   silver_participant_day_coverage         participant_day_missing    error           4  no minute-grain data arrived for this particip...

## Ad-hoc SQL over what's loaded

DuckDB queries straight over the DataFrames already in this notebook — no
registration step needed, same engine `gold.py` builds the tables with.
`is_complete_day` is the flag to filter on for volume metrics (steps); it
travels with the row rather than being applied at write time, so it's a
query-time decision here too.

In [22]:
daily = gold_tables["gold_daily_participant_metrics"]
devices = gold_tables["gold_participant_devices"]

duckdb.sql(
    """
    SELECT d.wear_site,
           count(*)                          AS participant_days,
           round(avg(m.steps_total), 0)      AS avg_daily_steps,
           round(avg(m.hr_resting_bpm), 1)   AS avg_resting_hr
    FROM daily m
    JOIN devices d USING (participant_id)
    WHERE m.is_complete_day
    GROUP BY 1
    ORDER BY avg_daily_steps DESC
    """
)

┌───────────────────┬──────────────────┬─────────────────┬────────────────┐
│     wear_site     │ participant_days │ avg_daily_steps │ avg_resting_hr │
│      varchar      │      int64       │     double      │     double     │
├───────────────────┼──────────────────┼─────────────────┼────────────────┤
│ wrist_nondominant │              557 │          9092.0 │           64.3 │
│ wrist_dominant    │              836 │          8856.0 │           61.5 │
└───────────────────┴──────────────────┴─────────────────┴────────────────┘

The query above answers one number per group. This one just hands back
rows to actually look at — the ten highest-activity complete participant-
days on record, unaggregated:

In [23]:
duckdb.sql(
    """
    SELECT participant_id, date, steps_total, active_minutes,
           hr_resting_bpm, sleep_efficiency_pct, coverage_pct
    FROM daily
    WHERE is_complete_day
    ORDER BY steps_total DESC
    LIMIT 10
    """
).df()

  participant_id        date  steps_total  active_minutes  hr_resting_bpm  sleep_efficiency_pct  coverage_pct
0           P035  2026-01-21      14749.0             970            63.0                 88.64         100.0
1           P035  2026-02-01      14680.0             966            63.0                 82.30         100.0
2           P035  2026-01-29      14672.0             966            63.0                 83.33         100.0
3           P035  2026-01-30      14663.0             959            62.0                 84.10         100.0
4           P035  2026-01-26      14585.0             968            63.0                 85.26         100.0
5           P035  2026-01-12      14574.0             957            63.0                 83.63         100.0
6           P035  2026-01-24      14562.0             955            63.0                 89.98         100.0
7           P035  2026-01-18      14556.0             962            63.0                 86.41         100.0
8           P035  2026-01-16      14504.0             947            63.0                 83.18         100.0
9           P035  2026-01-10      14490.0             961            52.0                 87.07         100.0